name       : adw-gtk3-theme
version    : '4.5'
release    : 4
source     :
    - https://github.com/lassekongo83/adw-gtk3/archive/refs/tags/v4.5.tar.gz : 3f42a87da8a8a4ca3a3377e522f772070014827b0970ba1735f131c27291c3b4
license    : LGPL-2.1-only
homepage   : https://github.com/lassekongo83/adw-gtk3
component  : desktop.theme
summary    : An unofficial GTK3 port of libadwaita
description: |
    An unofficial GTK3 port of libadwaita
builddeps  :
    - sassc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
