name       : adw-gtk3-theme
version    : '4.6'
release    : 5
source     :
    - https://github.com/lassekongo83/adw-gtk3/archive/refs/tags/v4.6.tar.gz : 28bb159118d3e8b6e04bbfdb897cc007c159ef5c480536961e2bd0eb9d393f25
license    : LGPL-2.1-only
homepage   : https://github.com/lassekongo83/adw-gtk3
component  : desktop.theme
summary    : An unofficial GTK3 port of libadwaita
description: |
    An unofficial GTK3 port of libadwaita
builddeps  :
    - sassc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
