name       : adw-gtk3-theme
version    : '4.1'
release    : 2
source     :
    - https://github.com/lassekongo83/adw-gtk3/archive/refs/tags/v4.1.tar.gz : c828a0c6080568ce13488a66e2593e14bbc69a94ff9416ebd2426583e12d986d
license    : LGPL-2.1-only
homepage   : https://github.com/lassekongo83/adw-gtk3
component  : desktop.theme
summary    : An unofficial GTK3 port of libadwaita
description: |
    An unofficial GTK3 port of libadwaita
builddeps  :
    - sassc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
