name       : adw-gtk3-theme
version    : '4.8'
release    : 8
source     :
    - https://github.com/lassekongo83/adw-gtk3/archive/refs/tags/v4.8.tar.gz : ba48963ff574a1cfed1d8249d6d50fc1872ccd03975e3006b808afdca64f3d44
license    : LGPL-2.1-only
homepage   : https://github.com/lassekongo83/adw-gtk3
component  : desktop.theme
summary    : An unofficial GTK3 port of libadwaita
description: |
    An unofficial GTK3 port of libadwaita
builddeps  :
    - sassc
    - gnome-themes-extra
rundeps    :
    - gnome-themes-extra
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Symlink adwaita gtk2 theme so we have _some_ gtk2 theming
    ln -sv /usr/share/themes/Adwaita/gtk-2.0/ $installdir/usr/share/themes/adw-gtk3/
    ln -sv /usr/share/themes/Adwaita-dark/gtk-2.0/ $installdir/usr/share/themes/adw-gtk3-dark/
